version: "3"

services:
  webapp:
    build:
      context: ./packages/webapp
      args:
        - app_version
    restart: unless-stopped

  backend:
    build: ./packages/backend
    environment:
      MN_PORT: 8000
      MN_DATABASE_URL: /data/markdown-notebook.sqlite
      MN_JWT_SECRET: ${JWT_SECRET}
    volumes:
      - "${DATABASE_STORAGE_DIR}:/data"
    restart: unless-stopped

  # The loadbalancer expects the webapp service to listen on port 80 and the
  # backend on port 8000.
  loadbalancer:
    build: ./packages/load-balancer
    depends_on:
      - webapp
      - backend
    ports:
      - "${PORT}:80"
    restart: unless-stopped
