[package]
name = "backend"
version = "0.1.0"
authors = ["Marvin Davieds <marvin.davieds@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.4", features = ["sqlite", "r2d2"] }
rocket = { version = "0.4.4", default-features = false }
rocket_cors = "0.5.2"
bcrypt = "0.7"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.0"
jsonwebtoken = "7"
chrono = { version = "0.4", features = ["serde"] }
rpassword = "4.0.5"
dotenv = "0.15.0"

[dependencies.rocket_contrib]
version = "0.4.4"
default-features = false
features = ["json", "serve"]
