name: CI

on:
  push:
    branches: [master]

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Init
        run: yarn install

      - name: Build frontend
        run: |
          cd packages/app
          yarn build

      - name: Deploy frontend
        run: |
          rm -rf /var/www/notes.marvindv.dev/html
          mkdir /var/www/notes.marvindv.dev/html
          mv ./packages/app/build/* /var/www/notes.marvindv.dev/html
