name: CI

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Run docker-compose
        env:
          JWT_SECRET: "${{ secrets.DEPLOY_JWT_SECRET }}"
          PORT: "${{ secrets.DEPLOY_PORT }}"
          DATABASE_STORAGE_DIR: "${{ secrets.DEPLOY_DATABASE_STORAGE_DIR }}"
        run: |
          docker-compose build
          docker-compose up -d
